# Generated by Django 3.2.2 on 2021-05-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='Rut')),
                ('nombre_apoderado', models.CharField(max_length=50, verbose_name='Nombre apoderado')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('telefono_apoderado', models.CharField(max_length=15, verbose_name='Telefono apoderado')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'db_table': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('0', 'Femenino'), ('1', 'Masculino'), ('2', 'No especifica')], max_length=1, verbose_name='Sexo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('estado', models.CharField(choices=[('0', 'Regular'), ('1', 'Se fué'), ('2', 'Finalizado')], max_length=1, verbose_name='estado')),
                ('rut_apoderado', models.ForeignKey(max_length=13, on_delete=django.db.models.deletion.CASCADE, to='alumnos.apoderado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumnos',
            },
        ),
    ]
