# Generated by Django 3.2.2 on 2021-06-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
