# Generated by Django 3.2.2 on 2021-07-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido_paterno', 'apellido_materno'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
