# Generated by Django 3.2.2 on 2021-05-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20210522_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='apoderado',
            order_with_respect_to='nombre_apoderado',
        ),
    ]
