# Generated by Django 3.2.2 on 2021-05-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20210526_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoderado',
            options={'ordering': ['nombre_apoderado', 'apellido_paterno'], 'verbose_name': 'Apoderado', 'verbose_name_plural': 'Apoderados'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='apoderado',
            order_with_respect_to=None,
        ),
    ]
