# Generated by Django 3.2.2 on 2021-06-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20210526_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut_apoderado',
            field=models.ForeignKey(max_length=13, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.apoderado'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='correo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Correo'),
        ),
    ]
