# Generated by Django 3.2.2 on 2021-06-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together={('semestres', 'año')},
        ),
    ]
