# Generated by Django 3.2.2 on 2021-07-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursoManager',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='año',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together={('semestres', 'year')},
        ),
    ]
