# Generated by Django 3.2.2 on 2021-06-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_alter_asignatura_nombre'),
        ('cursos', '0002_alter_fecha_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignatura_curso',
            unique_together={('curso', 'asignatura')},
        ),
    ]
