# Generated by Django 3.2.2 on 2021-07-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='year',
            field=models.CharField(choices=[('100', '2021'), ('99', '2020'), ('98', '2019'), ('97', '2018'), ('96', '2017'), ('95', '2016'), ('94', '2015'), ('93', '2014'), ('92', '2013'), ('91', '2012'), ('90', '2011'), ('89', '2010'), ('88', '2009'), ('87', '2008'), ('86', '2007'), ('85', '2006'), ('84', '2005'), ('83', '2004'), ('82', '2003'), ('81', '2002'), ('80', '2001'), ('79', '2000')], max_length=4, verbose_name='Año'),
        ),
    ]
