# Generated by Django 3.2.2 on 2021-06-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_asignatura_curso_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='asignaturas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cod_fecha',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_prof_jefe',
        ),
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='asig_impartir',
        ),
        migrations.DeleteModel(
            name='Asignatura_Curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Fecha',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
