# Generated by Django 3.2.2 on 2021-07-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_fecha_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='year',
            field=models.IntegerField(max_length=4, verbose_name='Año'),
        ),
    ]
