# Generated by Django 3.2.2 on 2021-07-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_fecha_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_prof_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to='cursos.profesor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='letra',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='plan_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='cursos.planestudio'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
