# Generated by Django 3.2.2 on 2021-07-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_curso_letra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['numero'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
    ]
