# Generated by Django 3.2.2 on 2021-07-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20210704_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='numero',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
