# Generated by Django 3.2.2 on 2021-07-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='numero',
            field=models.FloatField(verbose_name='Numero'),
        ),
    ]
