# Generated by Django 3.2.2 on 2021-07-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='numero',
        ),
    ]
