# Generated by Django 3.2.2 on 2021-07-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_auto_20210704_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['numero'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='numero',
            field=models.FloatField(blank=True, null=True, verbose_name='Numero'),
        ),
    ]
