# Generated by Django 3.2.2 on 2021-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
