# Generated by Django 3.2.2 on 2021-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
