# Generated by Django 3.2.2 on 2021-06-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rol_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
