# Generated by Django 3.2.2 on 2021-07-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_ausente', models.IntegerField(verbose_name='Dias ausente')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
                'db_table': 'Antecedentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50, verbose_name='Nombre tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Antecedente_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antecedentes.antecedente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antecedentes.tipo')),
            ],
            options={
                'db_table': 'Antecedente_tipo',
            },
        ),
        migrations.AddField(
            model_name='antecedente',
            name='antecedentes',
            field=models.ManyToManyField(through='antecedentes.Antecedente_tipo', to='antecedentes.Tipo'),
        ),
    ]
